#!/usr/bin/env python3
"""
EasyDeploy generator: reads app.yaml → produces Helm values, ArgoCD ApplicationSet, RUNBOOK.

Monorepo mode (default):
  ./generator/generate.py apps/hello-world/app.yaml

Standalone mode (per-app repo — pass the repo's GitHub URL as second arg):
  ./generate.py app.yaml https://github.com/easydeploytest/my-app
"""
import sys
import os
import yaml
import textwrap

CLUSTER_IP = "135.181.177.246"
REGISTRY = "registry.easy-deploy.135.181.177.246.nip.io"
INFISICAL_HOST = "http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080"
ARGOCD_REPO = "https://github.com/easydeploytest/EasyDeploy.git"
NTFY_URL = "https://ntfy.sh/easydeploy-cicd-7x4k2"
INFISICAL_URL = "https://infisical.easy-deploy.135.181.177.246.nip.io"
INFISICAL_ORG_ID = "058c91f2-63c4-4a9b-a58a-74855d18f167"
ARGOCD_URL = "https://argocd.easy-deploy.135.181.177.246.nip.io"


def load_app(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def write(path: str, content: str):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {path}")


def generate_helm_values(app: dict, env: str) -> str:
    name = app["name"]
    team = app["team"]
    port = app.get("port", 3000)
    resources = app.get("resources", {})
    scaling = app.get("scaling", {})
    health = app.get("health", {})
    auth = app.get("auth", {})

    values = {
        "name": name,
        "team": team,
        "env": env,
        "port": port,
        "clusterIP": CLUSTER_IP,
        "infisicalHost": INFISICAL_HOST,
        "image": f"{REGISTRY}/easy-deploy/{name}:latest",
        "imagePullPolicy": "Always",
        "resources": resources or {
            "requests": {"cpu": "100m", "memory": "256Mi"},
            "limits": {"cpu": "500m", "memory": "512Mi"},
        },
        "scaling": {
            "min": scaling.get("min", 1),
            "max": scaling.get("max", 3),
            "cpu_target": scaling.get("cpu_target", 80),
        },
        "health": {"startup_delay": health.get("startup_delay", 10)},
        "auth": {
            "require_auth": auth.get("require_auth", False),
            "attributes": auth.get("attributes", []),
        },
    }
    return yaml.dump(values, default_flow_style=False)


def generate_appset(app: dict, repo_url: str, chart_path: str, values_pattern: str) -> str:
    name = app["name"]
    return textwrap.dedent(f"""\
        apiVersion: argoproj.io/v1alpha1
        kind: ApplicationSet
        metadata:
          name: {name}
          namespace: argocd
        spec:
          generators:
            - list:
                elements:
                  - env: dev
                  - env: prod
          template:
            metadata:
              name: "{name}-{{{{env}}}}"
              annotations:
                notifications.argoproj.io/subscribe.on-deployed.ntfy: ''
                notifications.argoproj.io/subscribe.on-health-degraded.ntfy: ''
                notifications.argoproj.io/subscribe.on-sync-failed.ntfy: ''
            spec:
              project: default
              source:
                repoURL: {repo_url}
                targetRevision: main
                path: {chart_path}
                helm:
                  valueFiles:
                    - {values_pattern}
              destination:
                server: https://kubernetes.default.svc
                namespace: "{name}-{{{{env}}}}"
              syncPolicy:
                automated:
                  prune: true
                  selfHeal: true
                syncOptions:
                  - CreateNamespace=true
    """)


def generate_runbook(app: dict) -> str:
    name = app["name"]
    team = app["team"]
    return textwrap.dedent(f"""\
        # {name} — RUNBOOK

        > Auto-generated by EasyDeploy generator. Do not edit manually.

        ## Environments

        | | URL |
        |---|---|
        | **dev** | https://{name}-dev.{team}.{CLUSTER_IP}.nip.io |
        | **prod** | https://{name}.{team}.{CLUSTER_IP}.nip.io |

        ## Observability

        | | |
        |---|---|
        | **Grafana** | https://shanzindlr.grafana.net |
        | **ArgoCD** | {ARGOCD_URL}/applications?search={name} |
        | **Infisical** | {INFISICAL_URL} — project: **{name}** |

        ## Deployments

        - **dev** — push to `main` → CI builds image, updates values, ArgoCD syncs automatically
        - **prod** — publish a GitHub Release with tag `v<version>` → CI re-tags image, ArgoCD syncs prod

        ## Secrets

        Manage environment variables in Infisical:
        {INFISICAL_URL} — project: **{name}**

        Changes are picked up within ~5 minutes — no redeploy needed.
    """)


def generate_readme(app: dict) -> str:
    name = app["name"]
    team = app["team"]
    return textwrap.dedent(f"""\
        # {name}

        Deployed on [EasyDeploy](https://github.com/easydeploytest/EasyDeploy) — k3s + ArgoCD + Infisical + OTEL → Grafana Cloud.

        | | |
        |---|---|
        | **Dev** | https://{name}-dev.{team}.{CLUSTER_IP}.nip.io |
        | **Prod** | https://{name}.{team}.{CLUSTER_IP}.nip.io |
        | **ArgoCD** | {ARGOCD_URL}/applications?search={name} |
        | **Infisical** | {INFISICAL_URL} — project **{name}** |
        | **Grafana** | https://shanzindlr.grafana.net |

        ## Getting started

        1. Edit `app.yaml` — set `name`, `team`, `port` to match your app
        2. Write your app in `src/` and update `Dockerfile`
        3. Push to `main` — CI builds the image and deploys to dev automatically

        ## Deploying to prod

        Publish a GitHub Release with tag `v<version>` (e.g. `v1.0.0`).
        CI re-tags the latest image as that version and ArgoCD syncs the prod namespace.

        ## Secrets

        Add secrets in [Infisical]({INFISICAL_URL}) → project **{name}** → environment **dev** or **prod**.
        They appear in your app as environment variables within ~5 minutes, no redeploy needed.

        ## Required GitHub Secrets

        Set these once under **Settings → Secrets and variables → Actions** (org-level covers all repos):

        | Secret | Description |
        |--------|-------------|
        | `ARGOCD_PASSWORD` | ArgoCD admin password |
        | `INFISICAL_CLIENT_ID` | Infisical machine identity client ID |
        | `INFISICAL_CLIENT_SECRET` | Infisical machine identity client secret |
        | `INFISICAL_IDENTITY_ID` | Infisical machine identity ID |

        ## How it works

        ```
        push to main
          → CI builds Docker image → pushes to {REGISTRY}
          → CI creates Infisical project (idempotent)
          → CI creates k8s namespaces + infisical-auth secrets
          → CI updates values-dev.yaml with new image tag → commits back
          → CI applies ArgoCD ApplicationSet → triggers sync
          → ArgoCD deploys → sends ntfy notification when pod is healthy
        ```
    """)


def main():
    if len(sys.argv) < 2:
        print("Usage: generate.py <path/to/app.yaml> [repo-url]")
        print("  repo-url: GitHub repo URL for standalone mode (e.g. https://github.com/org/my-app)")
        sys.exit(1)

    app_yaml_path = sys.argv[1]
    repo_url = sys.argv[2] if len(sys.argv) > 2 else None
    standalone = repo_url is not None

    app = load_app(app_yaml_path)
    name = app["name"]
    app_dir = os.path.dirname(app_yaml_path) or "."

    print(f"Generating for app: {name} ({'standalone' if standalone else 'monorepo'} mode)")

    if standalone:
        # Per-app repo: all outputs go next to app.yaml; Helm chart lives at chart/
        for env in ("dev", "prod"):
            write(f"{app_dir}/values-{env}.yaml", generate_helm_values(app, env))
        write(
            f"{app_dir}/argocd-appset.yaml",
            generate_appset(app, repo_url, "chart", "../values-{{env}}.yaml"),
        )
        write(f"{app_dir}/RUNBOOK.md", generate_runbook(app))
        write(f"{app_dir}/README.md", generate_readme(app))
    else:
        # Monorepo: values under apps/<name>/, AppSet under argocd/
        for env in ("dev", "prod"):
            write(f"{app_dir}/values-{env}.yaml", generate_helm_values(app, env))
        write(
            f"argocd/{name}-appset.yaml",
            generate_appset(app, ARGOCD_REPO, "charts/app", f"../../apps/{name}/values-{{{{env}}}}.yaml"),
        )
        write(f"{app_dir}/RUNBOOK.md", generate_runbook(app))

    print("Done.")


if __name__ == "__main__":
    main()
