apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.name }}-{{ .Values.env }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.scaling.min }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "opentelemetry-operator-system/otel-instrumentation"
    spec:
      imagePullSecrets:
        - name: easydeploy-registry-creds
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          # Secrets from Infisical via ExternalSecret → K8s Secret
          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}
                optional: true
          # OTEL auto-instrumentation
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.name }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetry-stack-daemon-collector.opentelemetry-operator-system.svc.cluster.local:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.team={{ .Values.team }},deployment.environment={{ .Values.env }}"
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.health.startup_delay }}
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.health.startup_delay }}
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
