{{- if .Values.infisicalHost }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.name }}-{{ .Values.env }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: SecretStore
    name: infisical-{{ .Values.name }}
  dataFrom:
    - find:
        name:
          regexp: ".*"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ include "app.fullname" . }}
{{- end }}
