apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.name }}-{{ .Values.env }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: {{ include "app.domain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ include "app.domain" . }}
      secretName: {{ include "app.fullname" . }}-tls
