apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.name }}-{{ .Values.env }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
